services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio-init:
    image: python:3.11-slim
    container_name: minio-init
    working_dir: /app
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
    command: sh -c "pip install minio && python scripts/init_minio.py"
    volumes:
      - ./scripts:/app/scripts

  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      minio-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: sh -c "pip install mlflow psycopg2-binary boto3 && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://postgres:password@postgres:5432/db --default-artifact-root s3://mlflow-artifacts --allowed-hosts mlflow,mlflow:5000,localhost,localhost:5000"

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    depends_on:
      minio-init:
        condition: service_completed_successfully
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
      KAGGLE_USERNAME: sebastioneto05
      KAGGLE_KEY: 668adff75b2763a38ba52a8b4f72dd1f

  transform_silver:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      ingest:
        condition: service_completed_successfully
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
    command: python scripts/bronze_to_silver.py

  transform_gold:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      transform_silver:
        condition: service_completed_successfully
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
    command: python scripts/silver_to_gold.py

  model_training:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      transform_gold:
        condition: service_completed_successfully
      mlflow:
        condition: service_started
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: python scripts/train_model.py

  model_training_bomb:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      transform_gold:
        condition: service_completed_successfully
      mlflow:
        condition: service_started
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: python scripts/train_bomb_model.py

    # ----------------- SPRINT 5 ----------------- #
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:  
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://12.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  milvus:
    image: milvusdb/milvus:v2.3.5
    container_name: milvus-standalone
    restart: unless-stopped
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_ACCESS_KEY: minioadmin
      MINIO_BUCKET_NAME: milvus-bucket
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530" # Porta principal de conexão do Milvus
      - "9091:9091"   # Porta para métricas/gerenciamento
    depends_on:
      - etcd
      - minio

volumes:
  postgres_data:
  minio_data:
  mlflow_data:
  etcd_data: # Volume novo pro Milvus
  milvus_data: # Volume novo pro Milvus
