services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlruns
    command: sh -c "pip install mlflow && mlflow server --host 0.0.0.0 --port 5000 --allowed-hosts mlflow,mlflow:5000,localhost,localhost:5000"

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
      KAGGLE_USERNAME: sebastioneto05
      KAGGLE_KEY: 668adff75b2763a38ba52a8b4f72dd1f

  transform_silver:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      ingest:
        condition: service_completed_successfully
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
    command: python scripts/bronze_to_silver.py

  transform_gold:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      transform_silver:
        condition: service_completed_successfully
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
    command: python scripts/silver_to_gold.py

  model_training:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      transform_gold:
        condition: service_completed_successfully
      mlflow:
        condition: service_started
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
      MLFLOW_TRACKING_URI: http://mlflow:5000
    command: python scripts/train_model.py

  model_training_bomb:
    build:
      context: .
      dockerfile: Dockerfile.transform_silver
    depends_on:
      transform_gold:
        condition: service_completed_successfully
      mlflow:
        condition: service_started
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
      MLFLOW_TRACKING_URI: http://mlflow:5000
    command: python scripts/train_bomb_model.py

volumes:
  postgres_data:
  minio_data:
  mlflow_data:
