FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --timeout 300 --retries 5 -r requirements.txt

COPY scripts /app/scripts

CMD ["python", "scripts/bronze_to_silver.py"]
